# 3-class artery/vein/background adaptation of vesselFM
experiment: av_ct
seed: 42

data:
  train_images: /projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/VesselFMAdaptationMethod/vesselFM-main/vesselFM-main/data/imagesTr_pre
  train_labels: /projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/VesselFMAdaptationMethod/vesselFM-main/vesselFM-main/data/labelsTr_pre
  val_images:   /projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/VesselFMAdaptationMethod/vesselFM-main/vesselFM-main/data/imagesVal_pre
  val_labels:   /projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/VesselFMAdaptationMethod/vesselFM-main/vesselFM-main/data/labelsVal_pre
  preprocessed: true
  spacing: null # [1.0, 1.0, 1.0]
  clip_hu: null # [-1000, 600]
  zscore: false # True if not preprocessing
  patch_size: [128, 128, 128]
  samples_per_volume: 6           # Was set to 4
  min_fg_fraction: 0.03            # hard-example mining, set back to default of 0.02 after testing
  labels:
    background: 0
    artery: 1
    vein: 2

model:
  num_classes: 3
  dropout: 0.2
  pretrain_ckpt: /projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/VesselFMAdaptationMethod/vesselFM-main/vesselFM-main/checkpoints/vesselFM_base.pt

loss:
  dice_ce_weight: 1.0
  class_weights: [0.05, 0.475, 0.475]   # tweak per dataset imbalance
  use_soft_cldice: true
  soft_cldice_weight_stage1: 0.5 # Default was 0.2
  soft_cldice_weight_stage2: 1.0
  soft_cldice_iters: 3

optim:
  lr_stage1: 3.0e-4 # Was 3.0e-4
  lr_stage2: 1.0e-4 # Was 3.0e-5
  weight_decay: 1.0e-5
  val_cldice_workers: 8 
  epochs_stage1: 100
  epochs_stage2: 20
  batch_size: 3
  amp: true

augment:
  gamma: [0.8, 1.2] # Was [0.7, 1.5]
  noise_std: 0.01
  flip_prob: 0.5
  elastic_prob: 0.0 # Turn off while tuning

inference:
  tta: false
  sigmoid_threshold: 0.5
  keep_small_cc_voxels: 50
