defaults:
  - hydra: default
  - model: dyn_unet_base
  - _self_

# i/o
image_path: /projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/VesselFMAdaptationMethod/vesselFM-main/vesselFM-main/data/imagesVal_pre #TODO
image_file_ending: nii.gz
output_folder: /projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/VesselFMAdaptationMethod/av_newmasks # TODO
image_dir: /projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/VesselFMAdaptationMethod/vesselFM-main/vesselFM-main/data/imagesVal_pre
mask_dir:  /projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/VesselFMAdaptationMethod/vesselFM-main/vesselFM-main/data/labelsVal_pre
raw_image_dir: null
file_app: ""

mask_path: /projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/VesselFMAdaptationMethod/vesselFM-main/vesselFM-main/data/labelsVal_pre
round_to: 2

# model & ckpt
device: cuda:0
ckpt_path: /projectnb/ec500kb/projects/Fall_2025_Projects/Project_4_VesselFM/VesselFMAdaptationMethod/vesselFM-main/vesselFM-main/checkpoints/av_ct_best_cldice.pt

# sliding window inferer
batch_size: 2
patch_size: [96, 96, 96]
overlap: 0.5
mode: "constant"
sigma_scale: 0.125
padding_mode: "constant"
use_av_refine: true

# eval & reproducibility
seed: 42

# standard pre-processing transforms
transforms_config:
  - EnsureChannelFirst:
      channel_dim: "no_channel"
  - ToTensor:
      device: null

# test time augmentation
tta:
  scales: [1.0] #[0.5, 1, 1.5]
  invert: false
  invert_mean_thresh: 0.5
  equalize_hist: false
  hist_bins: 100

# post-processing
post:
  apply: false
  small_objects_min_size: 500
  small_objects_connectivity: 3

# merging
merging:
  threshold: 0.5
  max: false

# --- override model for A/V/BG ---
model:
  out_channels: 3