# -*- coding: utf-8 -*-
"""Finetune_VesselFM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15b44Wy1A7sgOI673RiSzFNackbgCDX3N
"""

import os
import time
from glob import glob

import torch
import torch.nn as nn
import torch.optim as optim

from monai.data import Dataset, DataLoader, CacheDataset
from monai.transforms import (
    LoadImaged, EnsureChannelFirstd, NormalizeIntensityd,
    RandSpatialCropSamplesd, RandFlipd, RandRotate90d,
    RandGaussianNoised, ScaleIntensityRangeD, Compose
)
from monai.inferers import sliding_window_inference
from monai.metrics import DiceMetric
from monai.networks.nets import DynUNet

class DiceLoss(nn.Module):
    def __init__(self, smooth=1e-5):
        super().__init__()
        self.smooth = smooth

    def forward(self, pred, target):
        pred = torch.sigmoid(pred)
        num = 2.0 * (pred * target).sum(dim=(2, 3, 4))
        den = pred.sum(dim=(2, 3, 4)) + target.sum(dim=(2, 3, 4)) + self.smooth
        dice = 1.0 - num / den
        return dice.mean()


def combined_loss(pred, target):
    bce = nn.BCEWithLogitsLoss()(pred, target)
    dice = DiceLoss()(pred, target)
    return 0.5 * bce + 0.5 * dice


def train_one_epoch(model, loader, optimizer, device, scaler=None):
    model.train()
    total_loss = 0.0
    for batch in loader:
        images = batch["image"].to(device)
        labels = batch["label"].to(device)
        optimizer.zero_grad()
        if scaler is not None:
            with torch.cuda.amp.autocast():
                outputs = model(images)
                loss = combined_loss(outputs, labels)
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            outputs = model(images)
            loss = combined_loss(outputs, labels)
            loss.backward()
            optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)


def validate(model, loader, device, roi_size, dice_metric):
    model.eval()
    total_loss = 0.0
    dice_metric.reset()

    with torch.no_grad():
        for batch in loader:
            images = batch["image"].to(device)
            labels = batch["label"].to(device)
            logits = sliding_window_inference(
                images,
                roi_size=roi_size,
                sw_batch_size=1,
                predictor=model,
            )
            loss = combined_loss(logits, labels)
            total_loss += loss.item()
            probs = torch.sigmoid(logits)
            preds = (probs > 0.5).float()
            dice_metric(y_pred=preds, y=labels)
    mean_dice = dice_metric.aggregate().item()
    return total_loss / len(loader), mean_dice

def main():
    image_dir = "/projectnb/ec500kb/projects/Project_4/Graph_Creations/Images/"
    mask_dir  = "/projectnb/ec500kb/projects/Project_4/Graph_Creations/Binary_Masks_Truth/"
    pretrained_ckpt = "vesselFM_base.pt"
    patch_size = (96, 96, 96)
    num_epochs = 50
    batch_size = 2
    num_workers = 4
    cache_rate = 0.5
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Using device:", device)
    images = sorted(glob(os.path.join(image_dir, "*.nii*")))
    masks  = sorted(glob(os.path.join(mask_dir, "*.nii*")))
    val_size = int(0.2 * len(images))
    train_images, val_images = images[val_size:], images[:val_size]
    train_masks,  val_masks  = masks[val_size:], masks[:val_size]
    train_files = [{"image": i, "label": m} for i, m in zip(train_images, train_masks)]
    val_files   = [{"image": i, "label": m} for i, m in zip(val_images,   val_masks)]
    print(f"Train volumes: {len(train_files)} | Val volumes: {len(val_files)}")
    patch_size = (96, 96, 96)
    train_transforms = Compose([
        LoadImaged(keys=["image", "label"]),
        EnsureChannelFirstd(keys=["image", "label"]),
        ScaleIntensityRangeD(
            keys=["image"],
            a_min=-1000,
            a_max=400,
            b_min=0.0,
            b_max=1.0,
            clip=True,
        ),
        NormalizeIntensityd(keys=["image"], nonzero=True, channel_wise=True),
        RandSpatialCropSamplesd(
            keys=["image", "label"],
            roi_size=patch_size,
            num_samples=4,
            random_center=True,
            random_size=False,
        ),
        RandFlipd(keys=["image", "label"], spatial_axis=[0], prob=0.5),
        RandFlipd(keys=["image", "label"], spatial_axis=[1], prob=0.5),
        RandFlipd(keys=["image", "label"], spatial_axis=[2], prob=0.5),
        RandRotate90d(keys=["image", "label"], prob=0.25, max_k=3),
        RandGaussianNoised(keys=["image"], prob=0.1),
    ])
    val_transforms = Compose([
        LoadImaged(keys=["image", "label"]),
        EnsureChannelFirstd(keys=["image", "label"]),
        ScaleIntensityRangeD(
            keys=["image"],
            a_min=-1000,
            a_max=400,
            b_min=0.0,
            b_max=1.0,
            clip=True,
        ),
        NormalizeIntensityd(keys=["image"], nonzero=True, channel_wise=True),
    ])
    train_ds = CacheDataset(
        data=train_files,
        transform=train_transforms,
        cache_rate=cache_rate,
        num_workers=num_workers,
    )
    val_ds = CacheDataset(
        data=val_files,
        transform=val_transforms,
        cache_rate=cache_rate,
        num_workers=num_workers,
    )

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True,
                              num_workers=num_workers, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size=1, shuffle=False,
                            num_workers=num_workers, pin_memory=True)

    model = DynUNet(
        spatial_dims=3,
        in_channels=1,
        out_channels=1,
        kernel_size=[[3, 3, 3]] * 6,
        strides=[[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]],
        upsample_kernel_size=[[2, 2, 2]] * 5,
        filters=[32, 64, 128, 256, 320, 320],
        res_block=True,
    )

    if os.path.exists(pretrained_ckpt):
        print(f"Loading pretrained weights from {pretrained_ckpt}")
        state_dict = torch.load(pretrained_ckpt, map_location="cpu")
        missing, unexpected = model.load_state_dict(state_dict, strict=False)
        print("Missing keys:", missing)
        print("Unexpected keys:", unexpected)
    else:
        print("WARNING: Pretrained checkpoint not found. Training from scratch.")

    model = model.to(device)

    freeze_encoder = True
    if freeze_encoder:
        print("Freezing encoder layers (input_block + downsamples)...")
        for p in model.input_block.parameters():
            p.requires_grad = False
        for p in model.downsamples.parameters():
            p.requires_grad = False

    optimizer = optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=1e-4,
        weight_decay=1e-5,
    )

    use_amp = True if device.type == "cuda" else False
    scaler = torch.cuda.amp.GradScaler() if use_amp else None
    dice_metric = DiceMetric(include_background=False, reduction="mean")
    best_dice = -1.0
    save_path = "vesselfm_finetuned_monai.pt"
    for epoch in range(num_epochs):
        start_time = time.time()
        train_loss = train_one_epoch(model, train_loader, optimizer, device, scaler)
        val_loss, val_dice = validate(model, val_loader, device, patch_size, dice_metric)

        elapsed = time.time() - start_time
        print(
            f"[Epoch {epoch+1:03d}/{num_epochs:03d}] "
            f"TrainLoss={train_loss:.4f} | "
            f"ValLoss={val_loss:.4f} | "
            f"ValDice={val_dice:.4f} | "
            f"Time={elapsed:.1f}s"
        )
        if val_dice > best_dice:
            best_dice = val_dice
            torch.save(model.state_dict(), save_path)
            print(f"  ✓ New best model saved to {save_path} (Dice={best_dice:.4f})")
    print("Training complete.")
    print(f"Best validation Dice: {best_dice:.4f}")
    print(f"Best model path: {save_path}")

if __name__ == "__main__":
    main()

#CONVERT GROUND TRUTH INTO BINARY MASKS

import os

in_path = "/projectnb/ec500kb/projects/Project_4/Graph_Creations/Masks_Truth"

for filename in os.listdir(in_path):
    out_path = "/projectnb/ec500kb/projects/Project_4/Graph_Creations/Binary_Masks_Truth/"
    full_path = os.path.join(in_path, filename)
    name = os.path.basename(filename).replace(".nii.gz", "")
    number = name[-3:]
    labels_to_merge = [2,3]
    target_label = 1
    img = sitk.ReadImage(full_path)
    arr = sitk.GetArrayFromImage(img)
    mask = np.isin(arr, labels_to_merge)
    arr[mask] = target_label
    out_img = sitk.GetImageFromArray(arr)
    out_img.CopyInformation(img)
    out_path = out_path + 'binary_case_' + number + '.nii.gz'
    print(out_path)
    sitk.WriteImage(out_img, out_path, useCompression=True)